//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frontend_SPP.Resources.Home
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class R_Home
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R_Home()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Frontend_SPP.Resources.Home.R_Home", typeof(R_Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lainnya....
        /// </summary>
        public static string Contact_Us
        {
            get
            {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Laporan dan Informasi
        ///dalam Statistik.
        /// </summary>
        public static string FAQ
        {
            get
            {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;BERITA&lt;/b&gt; TERBARU.
        /// </summary>
        public static string Jenis_Pelanggaran
        {
            get
            {
                return ResourceManager.GetString("Jenis_Pelanggaran", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BUDAYA.
        /// </summary>
        public static string Login
        {
            get
            {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DAFTAR &lt;b&gt;INVESTIGASI&lt;/b&gt;.
        /// </summary>
        public static string Register
        {
            get
            {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LAYANAN &lt;b&gt;INFORMASI PUBLIK&lt;/b&gt;.
        /// </summary>
        public static string Statistik
        {
            get
            {
                return ResourceManager.GetString("Statistik", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;PUBLIKASI&lt;/b&gt; &amp; SIARAN PERS.
        /// </summary>
        public static string Tentang_SPP
        {
            get
            {
                return ResourceManager.GetString("Tentang_SPP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;GALERI&lt;/b&gt; FOTO.
        /// </summary>
        public static string Sistem_Pelaporan_Pelanggaran
        {
            get
            {
                return ResourceManager.GetString("Sistem_Pelaporan_Pelanggaran", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TAHUKAH&lt;/b&gt; ANDA?.
        /// </summary>
        public static string Konten1
        {
            get
            {
                return ResourceManager.GetString("Konten1", resourceCulture);
            }
        }

        public static string Lihat_Pedoman
        {
            get
            {
                return ResourceManager.GetString("Lihat_Pedoman", resourceCulture);
            }
        }

        public static string Subtitle2
        {
            get
            {
                return ResourceManager.GetString("Subtitle2", resourceCulture);
            }
        }

        public static string RAHASIA
        {
            get
            {
                return ResourceManager.GetString("RAHASIA", resourceCulture);
            }
        }

        public static string TIDAK_MEMIHAK
        {
            get
            {
                return ResourceManager.GetString("TIDAK_MEMIHAK", resourceCulture);
            }
        }

        public static string INDEPENDEN
        {
            get
            {
                return ResourceManager.GetString("INDEPENDEN", resourceCulture);
            }
        }

        public static string Konten_Rahasia
        {
            get
            {
                return ResourceManager.GetString("Konten_Rahasia", resourceCulture);
            }
        }

        public static string Konten_Tidak_Memihak
        {
            get
            {
                return ResourceManager.GetString("Konten_Tidak_Memihak", resourceCulture);
            }
        }

        public static string Konten_Independen
        {
            get
            {
                return ResourceManager.GetString("Konten_Independen", resourceCulture);
            }
        }

        public static string Kriteria_Pelanggaran { get { return ResourceManager.GetString("Kriteria_Pelanggaran", resourceCulture); } }
        public static string Sub_Kriteria_Pelanggaran { get { return ResourceManager.GetString("Sub_Kriteria_Pelanggaran", resourceCulture); } }
        public static string Peraturan_Undang { get { return ResourceManager.GetString("Peraturan_Undang", resourceCulture); } }
        public static string Pedoman_Kode_Etik { get { return ResourceManager.GetString("Pedoman_Kode_Etik", resourceCulture); } }
        public static string Kebijakan_Dan_Prosedur { get { return ResourceManager.GetString("Kebijakan_Dan_Prosedur", resourceCulture); } }
        public static string Akuntansi_Keuangan { get { return ResourceManager.GetString("Akuntansi_Keuangan", resourceCulture); } }
        public static string Wewenang_Atau_Jabatan { get { return ResourceManager.GetString("Wewenang_Atau_Jabatan", resourceCulture); } }
        public static string Praktek_Gratifikasi { get { return ResourceManager.GetString("Praktek_Gratifikasi", resourceCulture); } }
        public static string Sub_Peraturan_Undang { get { return ResourceManager.GetString("Sub_Peraturan_Undang", resourceCulture); } }
        public static string Sub_Pedoman_Kode_Etik { get { return ResourceManager.GetString("Sub_Pedoman_Kode_Etik", resourceCulture); } }
        public static string Sub_Kebijakan_Dan_Prosedur { get { return ResourceManager.GetString("Sub_Kebijakan_Dan_Prosedur", resourceCulture); } }
        public static string Sub_Akuntansi_Keuangan { get { return ResourceManager.GetString("Sub_Akuntansi_Keuangan", resourceCulture); } }
        public static string Sub_Wewenang_Atau_Jabatan { get { return ResourceManager.GetString("Sub_Wewenang_Atau_Jabatan", resourceCulture); } }
        public static string Sub_Praktek_Gratifikasi { get { return ResourceManager.GetString("Sub_Praktek_Gratifikasi", resourceCulture); } }

        public static string Media_Penyampaian_Laporan { get { return ResourceManager.GetString("Media_Penyampaian_Laporan", resourceCulture); } }
        public static string Sub_Media_Penyampaian_Laporan { get { return ResourceManager.GetString("Sub_Media_Penyampaian_Laporan", resourceCulture); } }
        public static string Informasi_Statistik { get { return ResourceManager.GetString("Informasi_Statistik", resourceCulture); } }
        public static string Konten_Contact_Us { get { return ResourceManager.GetString("Konten_Contact_Us", resourceCulture); } }
        public static string Phone { get { return ResourceManager.GetString("Phone", resourceCulture); } }
        public static string Faximile { get { return ResourceManager.GetString("Faximile", resourceCulture); } }
        public static string Email_Us { get { return ResourceManager.GetString("Email_Us", resourceCulture); } }
        public static string Register_Sebagai_Whistleblower { get { return ResourceManager.GetString("Register_Sebagai_Whistleblower", resourceCulture); } }
        public static string Nama { get { return ResourceManager.GetString("Nama", resourceCulture); } }
        public static string Nomor_Handphone { get { return ResourceManager.GetString("Nomor_Handphone", resourceCulture); } }
        public static string Saya_Menyatakan_Setuju { get { return ResourceManager.GetString("Saya_Menyatakan_Setuju", resourceCulture); } }
        public static string Lupa_Password { get { return ResourceManager.GetString("Lupa_Password", resourceCulture); } }
        public static string Input_Email_Anda_FP { get { return ResourceManager.GetString("Input_Email_Anda_FP", resourceCulture); } }
        public static string Input_Email_Anda { get { return ResourceManager.GetString("Input_Email_Anda", resourceCulture); } }
        public static string Batal { get { return ResourceManager.GetString("Batal", resourceCulture); } }
        public static string Gunakan_Nomor_Handphone { get { return ResourceManager.GetString("Gunakan_Nomor_Handphone", resourceCulture); } }
        public static string Masukkan_Nomor_Handphone { get { return ResourceManager.GetString("Masukkan_Nomor_Handphone", resourceCulture); } }
        public static string Kirim_Otp { get { return ResourceManager.GetString("Kirim_Otp", resourceCulture); } }
        public static string Gunakan_Email { get { return ResourceManager.GetString("Gunakan_Email", resourceCulture); } }

        public static string Sistem_Pelaporan_Pelanggaran_Pt_Smi { get { return ResourceManager.GetString("Sistem_Pelaporan_Pelanggaran_Pt_Smi", resourceCulture); } }
        public static string Contactuscontent { get { return ResourceManager.GetString("Contactuscontent", resourceCulture); } }
        public static string Saya_Menyatakan_Setuju_Dengan { get { return ResourceManager.GetString("Saya_Menyatakan_Setuju_Dengan", resourceCulture); } }
        public static string Syarat_Dan_Ketentuan { get { return ResourceManager.GetString("Syarat_Dan_Ketentuan", resourceCulture); } }
        public static string Pulihkan_Akun { get { return ResourceManager.GetString("Pulihkan_Akun", resourceCulture); } }
        public static string Masukkan_Nomor_Handphone_Anda_Yang_Terdaftar { get { return ResourceManager.GetString("Masukkan_Nomor_Handphone_Anda_Yang_Terdaftar", resourceCulture); } }
        public static string Sub_Contact_Us { get { return ResourceManager.GetString("Sub_Contact_Us", resourceCulture); } }
        public static string InputkodeOTP { get { return ResourceManager.GetString("InputkodeOTP", resourceCulture); } }
        public static string KirimUlangKodeOTP { get { return ResourceManager.GetString("KirimUlangKodeOTP", resourceCulture); } }

        public static string FAQ1 { get { return ResourceManager.GetString("FAQ1", resourceCulture); } }
        public static string Answer1 { get { return ResourceManager.GetString("Answer1", resourceCulture); } }
        public static string FAQ2 { get { return ResourceManager.GetString("FAQ2", resourceCulture); } }
        public static string Answer2 { get { return ResourceManager.GetString("Answer2", resourceCulture); } }
        public static string FAQ3 { get { return ResourceManager.GetString("FAQ3", resourceCulture); } }
        public static string Answer3 { get { return ResourceManager.GetString("Answer3", resourceCulture); } }
        public static string FAQ4 { get { return ResourceManager.GetString("FAQ4", resourceCulture); } }
        public static string Answer4 { get { return ResourceManager.GetString("Answer4", resourceCulture); } }
        public static string FAQ5 { get { return ResourceManager.GetString("FAQ5", resourceCulture); } }
        public static string Answer5 { get { return ResourceManager.GetString("Answer5", resourceCulture); } }
        public static string FAQ6 { get { return ResourceManager.GetString("FAQ6", resourceCulture); } }
        public static string Answer6 { get { return ResourceManager.GetString("Answer6", resourceCulture); } }

        public static string Jan { get { return ResourceManager.GetString("Jan", resourceCulture); } }
        public static string Feb { get { return ResourceManager.GetString("Feb", resourceCulture); } }
        public static string Mar { get { return ResourceManager.GetString("Mar", resourceCulture); } }
        public static string Apr { get { return ResourceManager.GetString("Apr", resourceCulture); } }
        public static string Mei { get { return ResourceManager.GetString("Mei", resourceCulture); } }
        public static string Jun { get { return ResourceManager.GetString("Jun", resourceCulture); } }
        public static string Jul { get { return ResourceManager.GetString("Jul", resourceCulture); } }
        public static string Aug { get { return ResourceManager.GetString("Aug", resourceCulture); } }
        public static string Sep { get { return ResourceManager.GetString("Sep", resourceCulture); } }
        public static string Okt { get { return ResourceManager.GetString("Okt", resourceCulture); } }
        public static string Nop { get { return ResourceManager.GetString("Nop", resourceCulture); } }
        public static string Des { get { return ResourceManager.GetString("Des", resourceCulture); } }

        public static string LaporanbyPeriode { get { return ResourceManager.GetString("LaporanbyPeriode", resourceCulture); } }
        public static string LaporanbyMedia { get { return ResourceManager.GetString("LaporanbyMedia", resourceCulture); } }
        public static string LaporanbyJenisPelanggaran { get { return ResourceManager.GetString("LaporanbyJenisPelanggaran", resourceCulture); } }

        public static string TotalPengaduan { get { return ResourceManager.GetString("TotalPengaduan", resourceCulture); } }
        public static string Diproses { get { return ResourceManager.GetString("Diproses", resourceCulture); } }
        public static string Selesai { get { return ResourceManager.GetString("Selesai", resourceCulture); } }
        public static string Ditolak { get { return ResourceManager.GetString("Ditolak", resourceCulture); } }

        public static string SelamatdatangdiAplikasiSPPPTSMI { get { return ResourceManager.GetString("SelamatdatangdiAplikasiSPPPTSMI", resourceCulture); } }
        public static string Jumlah { get { return ResourceManager.GetString("Jumlah", resourceCulture); } }
        public static string Pengaduan { get { return ResourceManager.GetString("Pengaduan", resourceCulture); } }
        public static string DaftarPengaduan { get { return ResourceManager.GetString("DaftarPengaduan", resourceCulture); } }
        public static string PanduanPengguna { get { return ResourceManager.GetString("PanduanPengguna", resourceCulture); } }
        public static string SPPPTSMI { get { return ResourceManager.GetString("SPPPTSMI", resourceCulture); } }
        public static string BuatPengaduanBaru { get { return ResourceManager.GetString("BuatPengaduanBaru", resourceCulture); } }
        public static string StatusPengaduan { get { return ResourceManager.GetString("StatusPengaduan", resourceCulture); } }
        public static string NomorTiket { get { return ResourceManager.GetString("NomorTiket", resourceCulture); } }
        public static string NamaPelapor { get { return ResourceManager.GetString("NamaPelapor", resourceCulture); } }
        public static string TanggalKejadian { get { return ResourceManager.GetString("TanggalKejadian", resourceCulture); } }
        public static string TanggalPengaduan { get { return ResourceManager.GetString("TanggalPengaduan", resourceCulture); } }
        public static string InformasiPengaduan { get { return ResourceManager.GetString("InformasiPengaduan", resourceCulture); } }
        public static string TambahData { get { return ResourceManager.GetString("TambahData", resourceCulture); } }
        public static string KirimPengaduan { get { return ResourceManager.GetString("KirimPengaduan", resourceCulture); } }
        public static string TanggapanPermintaanInformasi { get { return ResourceManager.GetString("TanggapanPermintaanInformasi", resourceCulture); } }
        public static string KirimTanggapan { get { return ResourceManager.GetString("KirimTanggapan", resourceCulture); } }
        public static string Selamatdatang { get { return ResourceManager.GetString("Selamatdatang", resourceCulture); } }
        public static string Semua { get { return ResourceManager.GetString("Semua", resourceCulture); } }
        public static string Terkirim { get { return ResourceManager.GetString("Terkirim", resourceCulture); } }
        public static string Respon { get { return ResourceManager.GetString("Respon", resourceCulture); } }
        public static string Departemen { get { return ResourceManager.GetString("Departemen", resourceCulture); } }
        public static string Jabatan { get { return ResourceManager.GetString("Jabatan", resourceCulture); } }
        public static string Foto { get { return ResourceManager.GetString("Foto", resourceCulture); } }
        public static string VerifikasiNomorHandphone { get { return ResourceManager.GetString("VerifikasiNomorHandphone", resourceCulture); } }
        public static string WajibDiisi { get { return ResourceManager.GetString("WajibDiisi", resourceCulture); } }
        public static string BelumDiproses { get { return ResourceManager.GetString("BelumDiproses", resourceCulture); } }

        public static string PortalSPP { get { return ResourceManager.GetString("PortalSPP", resourceCulture); } }
        public static string Surat { get { return ResourceManager.GetString("Surat", resourceCulture); } }
        public static string Telepon { get { return ResourceManager.GetString("Telepon", resourceCulture); } }
        public static string Fax { get { return ResourceManager.GetString("Fax", resourceCulture); } }
        public static string Mailbox { get { return ResourceManager.GetString("Mailbox", resourceCulture); } }
        public static string PihakTerlapor { get { return ResourceManager.GetString("PihakTerlapor", resourceCulture); } }






    }
}
