CREATE TABLE [dbo].[tblT_CMS] (
    [ID]          UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [ID_IN]       UNIQUEIDENTIFIER NULL,
    [Tipe]        VARCHAR (255)    NULL,
    [Lang]        VARCHAR (2)      NULL,
    [Title]       VARCHAR (255)    NULL,
    [SubTitle]    VARCHAR (255)    NULL,
    [GridTitle]   VARCHAR (255)    NULL,
    [GridContent] VARCHAR (MAX)    NULL,
    [LabelTombol] VARCHAR (50)     NULL,
    [Link]        VARCHAR (MAX)    NULL,
    [Description] VARCHAR (MAX)    NULL,
    [Filename]    VARCHAR (255)    NULL,
    [Ekstension]  VARCHAR (50)     NULL,
    [Filename1]   VARCHAR (255)    NULL,
    [Ekstension1] VARCHAR (50)     NULL,
    [Value1]      VARCHAR (MAX)    NULL,
    [Value2]      VARCHAR (MAX)    NULL,
    [Value3]      VARCHAR (MAX)    NULL,
    [Value4]      VARCHAR (MAX)    NULL,
    [Value5]      VARCHAR (MAX)    NULL,
    [Value6]      VARCHAR (MAX)    NULL,
    [Value7]      VARCHAR (MAX)    NULL,
    [Value8]      VARCHAR (MAX)    NULL,
    [Value9]      VARCHAR (MAX)    NULL,
    [Status]      VARCHAR (50)     NULL,
    [CreatedOn]   DATETIME         DEFAULT (getdate()) NOT NULL,
    [CreatedBy]   VARCHAR (200)    NULL,
    [UpdatedOn]   DATETIME         DEFAULT (getdate()) NULL,
    [UpdatedBy]   VARCHAR (200)    NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


